---
- name: "(hardware.ssacli) include os specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: ["always"]

- import_tasks: "install.yml"
  tags: ["role::ssacli", "task::install"]
