---
- name: "(hardware.firmware_amd) include os specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: ["always"]

- import_tasks: "install.yml"
  tags: ["role::firmware_amd", "task::install"]
